package rpcserver.server.producor;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_request.proto

public final class RpcRequestProto {
  private RpcRequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.RpcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string id = 1;</code>
     * @return A list containing the id.
     */
    java.util.List<String>
        getIdList();
    /**
     * <code>repeated string id = 1;</code>
     * @return The count of id.
     */
    int getIdCount();
    /**
     * <code>repeated string id = 1;</code>
     * @param index The index of the element to return.
     * @return The id at the given index.
     */
    String getId(int index);
    /**
     * <code>repeated string id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the id at the given index.
     */
    com.google.protobuf.ByteString
        getIdBytes(int index);

    /**
     * <code>repeated string className = 2;</code>
     * @return A list containing the className.
     */
    java.util.List<String>
        getClassNameList();
    /**
     * <code>repeated string className = 2;</code>
     * @return The count of className.
     */
    int getClassNameCount();
    /**
     * <code>repeated string className = 2;</code>
     * @param index The index of the element to return.
     * @return The className at the given index.
     */
    String getClassName(int index);
    /**
     * <code>repeated string className = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the className at the given index.
     */
    com.google.protobuf.ByteString
        getClassNameBytes(int index);

    /**
     * <code>repeated string methodName = 3;</code>
     * @return A list containing the methodName.
     */
    java.util.List<String>
        getMethodNameList();
    /**
     * <code>repeated string methodName = 3;</code>
     * @return The count of methodName.
     */
    int getMethodNameCount();
    /**
     * <code>repeated string methodName = 3;</code>
     * @param index The index of the element to return.
     * @return The methodName at the given index.
     */
    String getMethodName(int index);
    /**
     * <code>repeated string methodName = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the methodName at the given index.
     */
    com.google.protobuf.ByteString
        getMethodNameBytes(int index);
  }
  /**
   * Protobuf type {@code server.RpcRequest}
   */
  public static final class RpcRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.RpcRequest)
      RpcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcRequest.newBuilder() to construct.
    private RpcRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcRequest() {
      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      className_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RpcRequest();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RpcRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                id_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(s);
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                className_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              className_.add(s);
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                methodName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              methodName_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          id_ = id_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          className_ = className_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          methodName_ = methodName_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcRequestProto.internal_static_server_RpcRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcRequestProto.internal_static_server_RpcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcRequest.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList id_;
    /**
     * <code>repeated string id = 1;</code>
     * @return A list containing the id.
     */
    public com.google.protobuf.ProtocolStringList
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated string id = 1;</code>
     * @return The count of id.
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated string id = 1;</code>
     * @param index The index of the element to return.
     * @return The id at the given index.
     */
    public String getId(int index) {
      return id_.get(index);
    }
    /**
     * <code>repeated string id = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the id at the given index.
     */
    public com.google.protobuf.ByteString
        getIdBytes(int index) {
      return id_.getByteString(index);
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList className_;
    /**
     * <code>repeated string className = 2;</code>
     * @return A list containing the className.
     */
    public com.google.protobuf.ProtocolStringList
        getClassNameList() {
      return className_;
    }
    /**
     * <code>repeated string className = 2;</code>
     * @return The count of className.
     */
    public int getClassNameCount() {
      return className_.size();
    }
    /**
     * <code>repeated string className = 2;</code>
     * @param index The index of the element to return.
     * @return The className at the given index.
     */
    public String getClassName(int index) {
      return className_.get(index);
    }
    /**
     * <code>repeated string className = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the className at the given index.
     */
    public com.google.protobuf.ByteString
        getClassNameBytes(int index) {
      return className_.getByteString(index);
    }

    public static final int METHODNAME_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList methodName_;
    /**
     * <code>repeated string methodName = 3;</code>
     * @return A list containing the methodName.
     */
    public com.google.protobuf.ProtocolStringList
        getMethodNameList() {
      return methodName_;
    }
    /**
     * <code>repeated string methodName = 3;</code>
     * @return The count of methodName.
     */
    public int getMethodNameCount() {
      return methodName_.size();
    }
    /**
     * <code>repeated string methodName = 3;</code>
     * @param index The index of the element to return.
     * @return The methodName at the given index.
     */
    public String getMethodName(int index) {
      return methodName_.get(index);
    }
    /**
     * <code>repeated string methodName = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the methodName at the given index.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes(int index) {
      return methodName_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < id_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_.getRaw(i));
      }
      for (int i = 0; i < className_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, className_.getRaw(i));
      }
      for (int i = 0; i < methodName_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += computeStringSizeNoTag(id_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < className_.size(); i++) {
          dataSize += computeStringSizeNoTag(className_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getClassNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < methodName_.size(); i++) {
          dataSize += computeStringSizeNoTag(methodName_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMethodNameList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcRequest)) {
        return super.equals(obj);
      }
      RpcRequest other = (RpcRequest) obj;

      if (!getIdList()
          .equals(other.getIdList())) return false;
      if (!getClassNameList()
          .equals(other.getClassNameList())) return false;
      if (!getMethodNameList()
          .equals(other.getMethodNameList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      if (getClassNameCount() > 0) {
        hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
        hash = (53 * hash) + getClassNameList().hashCode();
      }
      if (getMethodNameCount() > 0) {
        hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMethodNameList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.RpcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.RpcRequest)
        RpcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcRequestProto.internal_static_server_RpcRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcRequestProto.internal_static_server_RpcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcRequest.class, Builder.class);
      }

      // Construct using RpcRequestProto.RpcRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        className_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcRequestProto.internal_static_server_RpcRequest_descriptor;
      }

      @Override
      public RpcRequest getDefaultInstanceForType() {
        return RpcRequest.getDefaultInstance();
      }

      @Override
      public RpcRequest build() {
        RpcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcRequest buildPartial() {
        RpcRequest result = new RpcRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          id_ = id_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) != 0)) {
          className_ = className_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.className_ = className_;
        if (((bitField0_ & 0x00000004) != 0)) {
          methodName_ = methodName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.methodName_ = methodName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcRequest) {
          return mergeFrom((RpcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcRequest other) {
        if (other == RpcRequest.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        if (!other.className_.isEmpty()) {
          if (className_.isEmpty()) {
            className_ = other.className_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureClassNameIsMutable();
            className_.addAll(other.className_);
          }
          onChanged();
        }
        if (!other.methodName_.isEmpty()) {
          if (methodName_.isEmpty()) {
            methodName_ = other.methodName_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureMethodNameIsMutable();
            methodName_.addAll(other.methodName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RpcRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RpcRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          id_ = new com.google.protobuf.LazyStringArrayList(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string id = 1;</code>
       * @return A list containing the id.
       */
      public com.google.protobuf.ProtocolStringList
          getIdList() {
        return id_.getUnmodifiableView();
      }
      /**
       * <code>repeated string id = 1;</code>
       * @return The count of id.
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated string id = 1;</code>
       * @param index The index of the element to return.
       * @return The id at the given index.
       */
      public String getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated string id = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the id at the given index.
       */
      public com.google.protobuf.ByteString
          getIdBytes(int index) {
        return id_.getByteString(index);
      }
      /**
       * <code>repeated string id = 1;</code>
       * @param index The index to set the value at.
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 1;</code>
       * @param value The id to add.
       * @return This builder for chaining.
       */
      public Builder addId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 1;</code>
       * @param values The id to add.
       * @return This builder for chaining.
       */
      public Builder addAllId(
          Iterable<String> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string id = 1;</code>
       * @param value The bytes of the id to add.
       * @return This builder for chaining.
       */
      public Builder addIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList className_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          className_ = new com.google.protobuf.LazyStringArrayList(className_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string className = 2;</code>
       * @return A list containing the className.
       */
      public com.google.protobuf.ProtocolStringList
          getClassNameList() {
        return className_.getUnmodifiableView();
      }
      /**
       * <code>repeated string className = 2;</code>
       * @return The count of className.
       */
      public int getClassNameCount() {
        return className_.size();
      }
      /**
       * <code>repeated string className = 2;</code>
       * @param index The index of the element to return.
       * @return The className at the given index.
       */
      public String getClassName(int index) {
        return className_.get(index);
      }
      /**
       * <code>repeated string className = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the className at the given index.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes(int index) {
        return className_.getByteString(index);
      }
      /**
       * <code>repeated string className = 2;</code>
       * @param index The index to set the value at.
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameIsMutable();
        className_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string className = 2;</code>
       * @param value The className to add.
       * @return This builder for chaining.
       */
      public Builder addClassName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameIsMutable();
        className_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string className = 2;</code>
       * @param values The className to add.
       * @return This builder for chaining.
       */
      public Builder addAllClassName(
          Iterable<String> values) {
        ensureClassNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, className_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string className = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        className_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string className = 2;</code>
       * @param value The bytes of the className to add.
       * @return This builder for chaining.
       */
      public Builder addClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureClassNameIsMutable();
        className_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMethodNameIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          methodName_ = new com.google.protobuf.LazyStringArrayList(methodName_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @return A list containing the methodName.
       */
      public com.google.protobuf.ProtocolStringList
          getMethodNameList() {
        return methodName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @return The count of methodName.
       */
      public int getMethodNameCount() {
        return methodName_.size();
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @param index The index of the element to return.
       * @return The methodName at the given index.
       */
      public String getMethodName(int index) {
        return methodName_.get(index);
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the methodName at the given index.
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes(int index) {
        return methodName_.getByteString(index);
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @param index The index to set the value at.
       * @param value The methodName to set.
       * @return This builder for chaining.
       */
      public Builder setMethodName(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodNameIsMutable();
        methodName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @param value The methodName to add.
       * @return This builder for chaining.
       */
      public Builder addMethodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureMethodNameIsMutable();
        methodName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @param values The methodName to add.
       * @return This builder for chaining.
       */
      public Builder addAllMethodName(
          Iterable<String> values) {
        ensureMethodNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methodName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMethodName() {
        methodName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string methodName = 3;</code>
       * @param value The bytes of the methodName to add.
       * @return This builder for chaining.
       */
      public Builder addMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureMethodNameIsMutable();
        methodName_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.RpcRequest)
    }

    // @@protoc_insertion_point(class_scope:server.RpcRequest)
    private static final RpcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcRequest();
    }

    public static RpcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcRequest>
        PARSER = new com.google.protobuf.AbstractParser<RpcRequest>() {
      @Override
      public RpcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RpcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:server.RpcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string requestId = 1;</code>
     * @return A list containing the requestId.
     */
    java.util.List<String>
        getRequestIdList();
    /**
     * <code>repeated string requestId = 1;</code>
     * @return The count of requestId.
     */
    int getRequestIdCount();
    /**
     * <code>repeated string requestId = 1;</code>
     * @param index The index of the element to return.
     * @return The requestId at the given index.
     */
    String getRequestId(int index);
    /**
     * <code>repeated string requestId = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the requestId at the given index.
     */
    com.google.protobuf.ByteString
        getRequestIdBytes(int index);

    /**
     * <code>repeated int32 code = 2;</code>
     * @return A list containing the code.
     */
    java.util.List<Integer> getCodeList();
    /**
     * <code>repeated int32 code = 2;</code>
     * @return The count of code.
     */
    int getCodeCount();
    /**
     * <code>repeated int32 code = 2;</code>
     * @param index The index of the element to return.
     * @return The code at the given index.
     */
    int getCode(int index);

    /**
     * <code>repeated string errorMsg = 3;</code>
     * @return A list containing the errorMsg.
     */
    java.util.List<String>
        getErrorMsgList();
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @return The count of errorMsg.
     */
    int getErrorMsgCount();
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @param index The index of the element to return.
     * @return The errorMsg at the given index.
     */
    String getErrorMsg(int index);
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the errorMsg at the given index.
     */
    com.google.protobuf.ByteString
        getErrorMsgBytes(int index);
  }
  /**
   * Protobuf type {@code server.RpcResponse}
   */
  public static final class RpcResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:server.RpcResponse)
      RpcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcResponse.newBuilder() to construct.
    private RpcResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcResponse() {
      requestId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      code_ = emptyIntList();
      errorMsg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RpcResponse();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RpcResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                requestId_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              requestId_.add(s);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                code_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              code_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                code_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                code_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                errorMsg_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              errorMsg_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          requestId_ = requestId_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          code_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          errorMsg_ = errorMsg_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcRequestProto.internal_static_server_RpcResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcRequestProto.internal_static_server_RpcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcResponse.class, Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList requestId_;
    /**
     * <code>repeated string requestId = 1;</code>
     * @return A list containing the requestId.
     */
    public com.google.protobuf.ProtocolStringList
        getRequestIdList() {
      return requestId_;
    }
    /**
     * <code>repeated string requestId = 1;</code>
     * @return The count of requestId.
     */
    public int getRequestIdCount() {
      return requestId_.size();
    }
    /**
     * <code>repeated string requestId = 1;</code>
     * @param index The index of the element to return.
     * @return The requestId at the given index.
     */
    public String getRequestId(int index) {
      return requestId_.get(index);
    }
    /**
     * <code>repeated string requestId = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the requestId at the given index.
     */
    public com.google.protobuf.ByteString
        getRequestIdBytes(int index) {
      return requestId_.getByteString(index);
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList code_;
    /**
     * <code>repeated int32 code = 2;</code>
     * @return A list containing the code.
     */
    @Override
    public java.util.List<Integer>
        getCodeList() {
      return code_;
    }
    /**
     * <code>repeated int32 code = 2;</code>
     * @return The count of code.
     */
    public int getCodeCount() {
      return code_.size();
    }
    /**
     * <code>repeated int32 code = 2;</code>
     * @param index The index of the element to return.
     * @return The code at the given index.
     */
    public int getCode(int index) {
      return code_.getInt(index);
    }
    private int codeMemoizedSerializedSize = -1;

    public static final int ERRORMSG_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList errorMsg_;
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @return A list containing the errorMsg.
     */
    public com.google.protobuf.ProtocolStringList
        getErrorMsgList() {
      return errorMsg_;
    }
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @return The count of errorMsg.
     */
    public int getErrorMsgCount() {
      return errorMsg_.size();
    }
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @param index The index of the element to return.
     * @return The errorMsg at the given index.
     */
    public String getErrorMsg(int index) {
      return errorMsg_.get(index);
    }
    /**
     * <code>repeated string errorMsg = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the errorMsg at the given index.
     */
    public com.google.protobuf.ByteString
        getErrorMsgBytes(int index) {
      return errorMsg_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < requestId_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestId_.getRaw(i));
      }
      if (getCodeList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(codeMemoizedSerializedSize);
      }
      for (int i = 0; i < code_.size(); i++) {
        output.writeInt32NoTag(code_.getInt(i));
      }
      for (int i = 0; i < errorMsg_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMsg_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < requestId_.size(); i++) {
          dataSize += computeStringSizeNoTag(requestId_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getRequestIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < code_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(code_.getInt(i));
        }
        size += dataSize;
        if (!getCodeList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        codeMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < errorMsg_.size(); i++) {
          dataSize += computeStringSizeNoTag(errorMsg_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getErrorMsgList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcResponse)) {
        return super.equals(obj);
      }
      RpcResponse other = (RpcResponse) obj;

      if (!getRequestIdList()
          .equals(other.getRequestIdList())) return false;
      if (!getCodeList()
          .equals(other.getCodeList())) return false;
      if (!getErrorMsgList()
          .equals(other.getErrorMsgList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRequestIdCount() > 0) {
        hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
        hash = (53 * hash) + getRequestIdList().hashCode();
      }
      if (getCodeCount() > 0) {
        hash = (37 * hash) + CODE_FIELD_NUMBER;
        hash = (53 * hash) + getCodeList().hashCode();
      }
      if (getErrorMsgCount() > 0) {
        hash = (37 * hash) + ERRORMSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsgList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code server.RpcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:server.RpcResponse)
        RpcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcRequestProto.internal_static_server_RpcResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcRequestProto.internal_static_server_RpcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcResponse.class, Builder.class);
      }

      // Construct using RpcRequestProto.RpcResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        requestId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        code_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMsg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcRequestProto.internal_static_server_RpcResponse_descriptor;
      }

      @Override
      public RpcResponse getDefaultInstanceForType() {
        return RpcResponse.getDefaultInstance();
      }

      @Override
      public RpcResponse build() {
        RpcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcResponse buildPartial() {
        RpcResponse result = new RpcResponse(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          requestId_ = requestId_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.requestId_ = requestId_;
        if (((bitField0_ & 0x00000002) != 0)) {
          code_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.code_ = code_;
        if (((bitField0_ & 0x00000004) != 0)) {
          errorMsg_ = errorMsg_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.errorMsg_ = errorMsg_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcResponse) {
          return mergeFrom((RpcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcResponse other) {
        if (other == RpcResponse.getDefaultInstance()) return this;
        if (!other.requestId_.isEmpty()) {
          if (requestId_.isEmpty()) {
            requestId_ = other.requestId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRequestIdIsMutable();
            requestId_.addAll(other.requestId_);
          }
          onChanged();
        }
        if (!other.code_.isEmpty()) {
          if (code_.isEmpty()) {
            code_ = other.code_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureCodeIsMutable();
            code_.addAll(other.code_);
          }
          onChanged();
        }
        if (!other.errorMsg_.isEmpty()) {
          if (errorMsg_.isEmpty()) {
            errorMsg_ = other.errorMsg_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureErrorMsgIsMutable();
            errorMsg_.addAll(other.errorMsg_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RpcResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RpcResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList requestId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureRequestIdIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          requestId_ = new com.google.protobuf.LazyStringArrayList(requestId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @return A list containing the requestId.
       */
      public com.google.protobuf.ProtocolStringList
          getRequestIdList() {
        return requestId_.getUnmodifiableView();
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @return The count of requestId.
       */
      public int getRequestIdCount() {
        return requestId_.size();
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @param index The index of the element to return.
       * @return The requestId at the given index.
       */
      public String getRequestId(int index) {
        return requestId_.get(index);
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the requestId at the given index.
       */
      public com.google.protobuf.ByteString
          getRequestIdBytes(int index) {
        return requestId_.getByteString(index);
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @param index The index to set the value at.
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRequestIdIsMutable();
        requestId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @param value The requestId to add.
       * @return This builder for chaining.
       */
      public Builder addRequestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureRequestIdIsMutable();
        requestId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @param values The requestId to add.
       * @return This builder for chaining.
       */
      public Builder addAllRequestId(
          Iterable<String> values) {
        ensureRequestIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, requestId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        requestId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string requestId = 1;</code>
       * @param value The bytes of the requestId to add.
       * @return This builder for chaining.
       */
      public Builder addRequestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureRequestIdIsMutable();
        requestId_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList code_ = emptyIntList();
      private void ensureCodeIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          code_ = mutableCopy(code_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @return A list containing the code.
       */
      public java.util.List<Integer>
          getCodeList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(code_) : code_;
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @return The count of code.
       */
      public int getCodeCount() {
        return code_.size();
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @param index The index of the element to return.
       * @return The code at the given index.
       */
      public int getCode(int index) {
        return code_.getInt(index);
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @param index The index to set the value at.
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(
          int index, int value) {
        ensureCodeIsMutable();
        code_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @param value The code to add.
       * @return This builder for chaining.
       */
      public Builder addCode(int value) {
        ensureCodeIsMutable();
        code_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @param values The code to add.
       * @return This builder for chaining.
       */
      public Builder addAllCode(
          Iterable<? extends Integer> values) {
        ensureCodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, code_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        code_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList errorMsg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureErrorMsgIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          errorMsg_ = new com.google.protobuf.LazyStringArrayList(errorMsg_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @return A list containing the errorMsg.
       */
      public com.google.protobuf.ProtocolStringList
          getErrorMsgList() {
        return errorMsg_.getUnmodifiableView();
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @return The count of errorMsg.
       */
      public int getErrorMsgCount() {
        return errorMsg_.size();
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @param index The index of the element to return.
       * @return The errorMsg at the given index.
       */
      public String getErrorMsg(int index) {
        return errorMsg_.get(index);
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the errorMsg at the given index.
       */
      public com.google.protobuf.ByteString
          getErrorMsgBytes(int index) {
        return errorMsg_.getByteString(index);
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @param index The index to set the value at.
       * @param value The errorMsg to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMsg(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorMsgIsMutable();
        errorMsg_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @param value The errorMsg to add.
       * @return This builder for chaining.
       */
      public Builder addErrorMsg(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureErrorMsgIsMutable();
        errorMsg_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @param values The errorMsg to add.
       * @return This builder for chaining.
       */
      public Builder addAllErrorMsg(
          Iterable<String> values) {
        ensureErrorMsgIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, errorMsg_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMsg() {
        errorMsg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string errorMsg = 3;</code>
       * @param value The bytes of the errorMsg to add.
       * @return This builder for chaining.
       */
      public Builder addErrorMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureErrorMsgIsMutable();
        errorMsg_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:server.RpcResponse)
    }

    // @@protoc_insertion_point(class_scope:server.RpcResponse)
    private static final RpcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcResponse();
    }

    public static RpcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcResponse>
        PARSER = new com.google.protobuf.AbstractParser<RpcResponse>() {
      @Override
      public RpcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RpcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RpcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_server_RpcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_server_RpcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021rpc_request.proto\022\006server\"?\n\nRpcReques" +
      "t\022\n\n\002id\030\001 \003(\t\022\021\n\tclassName\030\002 \003(\t\022\022\n\nmeth" +
      "odName\030\003 \003(\t\"@\n\013RpcResponse\022\021\n\trequestId" +
      "\030\001 \003(\t\022\014\n\004code\030\002 \003(\005\022\020\n\010errorMsg\030\003 \003(\tB\023" +
      "\n\000B\017RpcRequestProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_server_RpcRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_server_RpcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RpcRequest_descriptor,
        new String[] { "Id", "ClassName", "MethodName", });
    internal_static_server_RpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_server_RpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_server_RpcResponse_descriptor,
        new String[] { "RequestId", "Code", "ErrorMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
